import 'package:flutter/material.dart';
import 'lookiva_api.dart';
import 'l10n.dart';
import 'account_actions.dart';

class CustomerRemotePage extends StatelessWidget{final String section;const CustomerRemotePage({super.key,required this.section});@override Widget build(BuildContext context){final config=CustomerRemoteBody.configFor(section);return Scaffold(appBar:AppBar(title:Text(ct(context,config.titleKey))),body:CustomerAccountActions.sections.contains(section)?CustomerAccountActions(section:section):CustomerRemoteBody(section:section));}}
class CustomerRemoteBody extends StatefulWidget{
  final String section;const CustomerRemoteBody({super.key,required this.section});
  static const config=<String,({String titleKey,String path,IconData icon})>{
    'account':(titleKey:'myAccount',path:'/customer-ops/dashboard',icon:Icons.person_rounded),'bookings':(titleKey:'myBookings',path:'/customer-ops/bookings',icon:Icons.calendar_month_rounded),'chat':(titleKey:'messages',path:'/customer-ops/conversations',icon:Icons.chat_bubble_outline_rounded),'retention':(titleKey:'retention',path:'/customer-ops/retention',icon:Icons.stars_rounded),'reviews':(titleKey:'myReviews',path:'/customer-ops/reviews',icon:Icons.rate_review_outlined),'favorites':(titleKey:'favorites',path:'/customer/favorites',icon:Icons.favorite_border_rounded),'collections':(titleKey:'collections',path:'/social-v2/collections',icon:Icons.collections_bookmark_outlined),'following':(titleKey:'following',path:'/customer/following',icon:Icons.person_add_alt_1_rounded),'notifications':(titleKey:'notifications',path:'/notifications',icon:Icons.notifications_none_rounded),'security':(titleKey:'security',path:'/auth/sessions',icon:Icons.security_rounded),'nearby-settings':(titleKey:'nearbySettings',path:'/customer/preferences',icon:Icons.location_on_outlined),'preferences':(titleKey:'preferences',path:'/customer/preferences',icon:Icons.tune_rounded)};
  static ({String titleKey,String path,IconData icon}) configFor(String section)=>config[section]??config['account']!;
  @override State<CustomerRemoteBody> createState()=>_CustomerRemoteBodyState();
}
class _CustomerRemoteBodyState extends State<CustomerRemoteBody>{
  late Future<dynamic> _future;({String titleKey,String path,IconData icon}) get config=>CustomerRemoteBody.configFor(widget.section);
  @override void initState(){super.initState();_reload();}@override void didUpdateWidget(covariant CustomerRemoteBody oldWidget){super.didUpdateWidget(oldWidget);if(oldWidget.section!=widget.section)_reload();}void _reload()=>_future=LookivaApi.instance.get(config.path);
  @override Widget build(BuildContext context)=>FutureBuilder<dynamic>(future:_future,builder:(context,snapshot){if(snapshot.connectionState==ConnectionState.waiting)return const _LoadingState();if(snapshot.hasError)return _ErrorState(message:LookivaApi.instance.friendlyError(snapshot.error!),onRetry:()=>setState(_reload));return RefreshIndicator(onRefresh:()async{setState(_reload);await _future;},child:_StructuredList(data:snapshot.data,icon:config.icon));});
}
class _StructuredList extends StatelessWidget{final dynamic data;final IconData icon;const _StructuredList({required this.data,required this.icon});
  @override Widget build(BuildContext context){final rows=_rows(context,data);if(rows.isEmpty)return ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(24),children:[const SizedBox(height:120),Icon(icon,size:52,color:Theme.of(context).colorScheme.primary),const SizedBox(height:16),Text(ct(context,'nothingHere'),textAlign:TextAlign.center,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:8),Text(ct(context,'pullRefresh'),textAlign:TextAlign.center,style:Theme.of(context).textTheme.bodyMedium)]);return ListView.separated(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(16),itemCount:rows.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(context,index){final row=rows[index];return Card(child:ListTile(leading:CircleAvatar(backgroundColor:Theme.of(context).colorScheme.primary.withValues(alpha: .14),foregroundColor:Theme.of(context).colorScheme.primary,child:Icon(icon)),title:Text(row.$1,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:row.$2.isEmpty?null:Text(row.$2,maxLines:5,overflow:TextOverflow.ellipsis)));});}
  List<(String,String)> _rows(BuildContext context,dynamic value){if(value==null)return const[];if(value is List)return value.map((item)=>_summarize(context,item)).toList();if(value is Map){final map=Map<String,dynamic>.from(value);final nestedLists=map.entries.where((e)=>e.value is List).toList();if(nestedLists.length==1&&map.length<=3)return(nestedLists.first.value as List).map((e)=>_summarize(context,e)).toList();return map.entries.map((e){if(e.value is Map||e.value is List)return(_label(e.key),_compact(context,e.value));return(_label(e.key),e.value?.toString()??'—');}).toList();}return[(ct(context,'details'),value.toString())];}
  (String,String) _summarize(BuildContext context,dynamic item){if(item is! Map)return(ct(context,'item'),item.toString());final map=Map<String,dynamic>.from(item);final company=map['company'] is Map?Map<String,dynamic>.from(map['company'] as Map):null;final title=_first(map,['display_name','name','title','full_name'])??company?['display_name']??map['status']??map['id']??ct(context,'item');final details=<String>[];final services=map['services'];if(services is List&&services.isNotEmpty&&services.first is Map){final first=Map<String,dynamic>.from(services.first as Map);final service=first['service'];if(service is Map&&service['name']!=null)details.add(service['name'].toString());}for(final key in['status','starts_at','created_at','currency_code','amount','body_plain']){final v=map[key];if(v!=null&&v.toString()!=title.toString())details.add('${_label(key)}: $v');if(details.length>=4)break;}return(title.toString(),details.join(' • '));}
  dynamic _first(Map<String,dynamic> map,List<String> keys){for(final key in keys){if(map[key]!=null&&map[key].toString().trim().isNotEmpty)return map[key];}return null;}String _compact(BuildContext context,dynamic value){if(value is List)return'${value.length} ${ct(context,'items')}';if(value is Map)return value.entries.take(5).map((e)=>'${_label(e.key.toString())}: ${e.value}').join(' • ');return value?.toString()??'—';}String _label(String value)=>value.replaceAll('_',' ').split(' ').map((w)=>w.isEmpty?w:'${w[0].toUpperCase()}${w.substring(1)}').join(' ');
}
class _LoadingState extends StatelessWidget{const _LoadingState();@override Widget build(BuildContext context)=>ListView.builder(padding:const EdgeInsets.all(16),itemCount:6,itemBuilder:(_,__)=>Card(child:Padding(padding:const EdgeInsets.all(22),child:LinearProgressIndicator(color:Theme.of(context).colorScheme.primary))));}
class _ErrorState extends StatelessWidget{final String message;final VoidCallback onRetry;const _ErrorState({required this.message,required this.onRetry});@override Widget build(BuildContext context)=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.cloud_off_rounded,size:54,color:Theme.of(context).colorScheme.error),const SizedBox(height:16),Text(ct(context,'unableLoad'),style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(message,textAlign:TextAlign.center),const SizedBox(height:18),ElevatedButton.icon(onPressed:onRetry,icon:const Icon(Icons.refresh_rounded),label:Text(ct(context,'retry')))])));}
