import enLocale from './locales/en.json';
import arLocale from './locales/ar.json';
import frLocale from './locales/fr.json';

export const supportedLocales = ['en', 'ar', 'fr'] as const;
export type SupportedLocale = (typeof supportedLocales)[number];
export const defaultLocale: SupportedLocale = 'en';

export const rtlLocales: SupportedLocale[] = ['ar'];

export const localeNames: Record<SupportedLocale, { native: string; english: string; flag: string }> = {
  en: { native: 'English', english: 'English', flag: '🇬🇧' },
  ar: { native: 'العربية', english: 'Arabic', flag: '🇱🇧' },
  fr: { native: 'Français', english: 'French', flag: '🇫🇷' },
};

export function isRtl(locale: string | undefined | null): boolean {
  if (!locale) return false;
  return (rtlLocales as readonly string[]).includes(locale);
}

export const locales = {
  en: enLocale,
  ar: arLocale,
  fr: frLocale,
} as const;

export type LocaleMessages = typeof enLocale;

type Join<K, P> = K extends string | number
  ? P extends string | number
    ? `${K}${'' extends P ? '' : '.'}${P}`
    : never
  : never;

type Prev = [never, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

type Leaves<T, D extends number = 5> = [D] extends [never]
  ? never
  : T extends object
  ? { [K in keyof T]-?: Join<K, Leaves<T[K], Prev[D]>> }[keyof T]
  : '';

export type TranslationKeys = Leaves<LocaleMessages>;

export const I18nKeys = {
  common: {
    actions: {
      save: 'common.actions.save',
      cancel: 'common.actions.cancel',
      edit: 'common.actions.edit',
      delete: 'common.actions.delete',
      submit: 'common.actions.submit',
      ok: 'common.actions.ok',
      yes: 'common.actions.yes',
      no: 'common.actions.no',
      retry: 'common.actions.retry',
      back: 'common.actions.back',
      next: 'common.actions.next',
      skip: 'common.actions.skip',
      share: 'common.actions.share',
      favorite: 'common.actions.favorite',
      unfavorite: 'common.actions.unfavorite',
      follow: 'common.actions.follow',
      unfollow: 'common.actions.unfollow',
      message: 'common.actions.message',
      call: 'common.actions.call',
      whatsapp: 'common.actions.whatsapp',
      directions: 'common.actions.directions',
      book: 'common.actions.book',
      bookNow: 'common.actions.bookNow',
      viewAll: 'common.actions.viewAll',
      seeMore: 'common.actions.seeMore',
      seeLess: 'common.actions.seeLess',
      loading: 'common.actions.loading',
      error: 'common.actions.error',
      empty: 'common.actions.empty',
      search: 'common.actions.search',
      searchPlaceholder: 'common.actions.searchPlaceholder',
      available: 'common.actions.available',
      verified: 'common.actions.verified',
      notAvailable: 'common.actions.notAvailable',
      comingSoon: 'common.actions.comingSoon',
      continue: 'common.actions.continue',
      confirm: 'common.actions.confirm',
      apply: 'common.actions.apply',
      clear: 'common.actions.clear',
      reset: 'common.actions.reset',
      close: 'common.actions.close',
      copy: 'common.actions.copy',
      copied: 'common.actions.copied',
      download: 'common.actions.download',
      upload: 'common.actions.upload',
      refresh: 'common.actions.refresh',
      showMore: 'common.actions.showMore',
      showLess: 'common.actions.showLess',
      readMore: 'common.actions.readMore',
      readLess: 'common.actions.readLess',
      select: 'common.actions.select',
      change: 'common.actions.change',
      remove: 'common.actions.remove',
      add: 'common.actions.add',
      create: 'common.actions.create',
      update: 'common.actions.update',
      view: 'common.actions.view',
      details: 'common.actions.details',
      learnMore: 'common.actions.learnMore',
      tryAgain: 'common.actions.tryAgain',
      goBack: 'common.actions.goBack',
      dismiss: 'common.actions.dismiss',
      accept: 'common.actions.accept',
      decline: 'common.actions.decline',
    },
    status: {
      success: 'common.status.success',
      warning: 'common.status.warning',
      info: 'common.status.info',
      danger: 'common.status.danger',
      active: 'common.status.active',
      inactive: 'common.status.inactive',
      pending: 'common.status.pending',
      processing: 'common.status.processing',
      completed: 'common.status.completed',
      cancelled: 'common.status.cancelled',
      expired: 'common.status.expired',
      scheduled: 'common.status.scheduled',
    },
    time: {
      today: 'common.time.today',
      tomorrow: 'common.time.tomorrow',
      yesterday: 'common.time.yesterday',
      now: 'common.time.now',
      minutes: 'common.time.minutes',
      hours: 'common.time.hours',
      days: 'common.time.days',
      weeks: 'common.time.weeks',
      months: 'common.time.months',
      years: 'common.time.years',
      am: 'common.time.am',
      pm: 'common.time.pm',
      to: 'common.time.to',
      from: 'common.time.from',
      at: 'common.time.at',
    },
    currency: {
      lbp: 'common.currency.lbp',
      usd: 'common.currency.usd',
      perHour: 'common.currency.perHour',
      perSession: 'common.currency.perSession',
      perPerson: 'common.currency.perPerson',
      startingAt: 'common.currency.startingAt',
      from: 'common.currency.from',
      to: 'common.currency.to',
      free: 'common.currency.free',
      paid: 'common.currency.paid',
      deposit: 'common.currency.deposit',
      perUnit: 'common.currency.perUnit',
    },
    feedback: {
      good: 'common.feedback.good',
      great: 'common.feedback.great',
      excellent: 'common.feedback.excellent',
      poor: 'common.feedback.poor',
      average: 'common.feedback.average',
      satisfied: 'common.feedback.satisfied',
      neutral: 'common.feedback.neutral',
      dissatisfied: 'common.feedback.dissatisfied',
    },
  },
  auth: {
    login: 'auth.login',
    register: 'auth.register',
    logout: 'auth.logout',
    forgotPassword: 'auth.forgotPassword',
    resetPassword: 'auth.resetPassword',
    verifyEmail: 'auth.verifyEmail',
    verifyPhone: 'auth.verifyPhone',
    sendOtp: 'auth.sendOtp',
    enterOtp: 'auth.enterOtp',
    email: 'auth.email',
    password: 'auth.password',
    confirmPassword: 'auth.confirmPassword',
    firstName: 'auth.firstName',
    lastName: 'auth.lastName',
    fullName: 'auth.fullName',
    phone: 'auth.phone',
    language: 'auth.language',
    iAcceptTerms: 'auth.iAcceptTerms',
    alreadyHaveAccount: 'auth.alreadyHaveAccount',
    dontHaveAccount: 'auth.dontHaveAccount',
    loginHere: 'auth.loginHere',
    signupHere: 'auth.signupHere',
    welcomeBack: 'auth.welcomeBack',
    welcomeToLookiva: 'auth.welcomeToLookiva',
    orContinueWith: 'auth.orContinueWith',
    google: 'auth.google',
    apple: 'auth.apple',
    facebook: 'auth.facebook',
    otpSentTo: 'auth.otpSentTo',
    otpExpiresIn: 'auth.otpExpiresIn',
    resendCode: 'auth.resendCode',
    codeNotReceived: 'auth.codeNotReceived',
    newPassword: 'auth.newPassword',
    currentPassword: 'auth.currentPassword',
    passwordHint: 'auth.passwordHint',
    passwordStrength: 'auth.passwordStrength',
    rememberMe: 'auth.rememberMe',
    biometricLogin: 'auth.biometricLogin',
    guestMode: 'auth.guestMode',
    termsOfService: 'auth.termsOfService',
    privacyPolicy: 'auth.privacyPolicy',
    loginSuccess: 'auth.loginSuccess',
    registerSuccess: 'auth.registerSuccess',
    logoutSuccess: 'auth.logoutSuccess',
    passwordChanged: 'auth.passwordChanged',
    emailVerified: 'auth.emailVerified',
    phoneVerified: 'auth.phoneVerified',
  },
  nav: {
    home: 'nav.home',
    discover: 'nav.discover',
    search: 'nav.search',
    map: 'nav.map',
    bookings: 'nav.bookings',
    profile: 'nav.profile',
    notifications: 'nav.notifications',
    messages: 'nav.messages',
    explore: 'nav.explore',
    categories: 'nav.categories',
    favorites: 'nav.favorites',
    following: 'nav.following',
    wallet: 'nav.wallet',
    settings: 'nav.settings',
    help: 'nav.help',
    menu: 'nav.menu',
  },
  homeSections: {
    forYou: 'homeSections.forYou',
    nearYou: 'homeSections.nearYou',
    availableNow: 'homeSections.availableNow',
    trending: 'homeSections.trending',
    topRated: 'homeSections.topRated',
    bestValue: 'homeSections.bestValue',
    lastMinute: 'homeSections.lastMinute',
    offers: 'homeSections.offers',
    newNearYou: 'homeSections.newNearYou',
    following: 'homeSections.following',
    recentlyViewed: 'homeSections.recentlyViewed',
    popularCategories: 'homeSections.popularCategories',
    recommendedProfessionals: 'homeSections.recommendedProfessionals',
    premiumPick: 'homeSections.premiumPick',
    editorChoice: 'homeSections.editorChoice',
    fastBooking: 'homeSections.fastBooking',
    staffPicks: 'homeSections.staffPicks',
    seasonalSpecials: 'homeSections.seasonalSpecials',
    weekendDeals: 'homeSections.weekendDeals',
  },
  business: {
    overview: 'business.overview',
    services: 'business.services',
    professionals: 'business.professionals',
    media: 'business.media',
    reviews: 'business.reviews',
    offers: 'business.offers',
    info: 'business.info',
    hours: 'business.hours',
    facilities: 'business.facilities',
    languages: 'business.languages',
    parking: 'business.parking',
    payments: 'business.payments',
    policies: 'business.policies',
    aboutUs: 'business.aboutUs',
    contactUs: 'business.contactUs',
    visitWebsite: 'business.visitWebsite',
    getDirections: 'business.getDirections',
    shareBusiness: 'business.shareBusiness',
    reportBusiness: 'business.reportBusiness',
    following: 'business.following',
    followBack: 'business.followBack',
    followers: 'business.followers',
    followingCount: 'business.followingCount',
    averageRating: 'business.averageRating',
    totalReviews: 'business.totalReviews',
    verifiedBadge: 'business.verifiedBadge',
    openNow: 'business.openNow',
    closedNow: 'business.closedNow',
    opensAt: 'business.opensAt',
    closesAt: 'business.closesAt',
    week: 'business.week',
    nextWeek: 'business.nextWeek',
    allDay: 'business.allDay',
    byAppointmentOnly: 'business.byAppointmentOnly',
    holidayHours: 'business.holidayHours',
    address: 'business.address',
    phoneNumber: 'business.phoneNumber',
    emailAddress: 'business.emailAddress',
    website: 'business.website',
    facebook: 'business.facebook',
    instagram: 'business.instagram',
    tiktok: 'business.tiktok',
    whatsappContact: 'business.whatsappContact',
    wifiAvailable: 'business.wifiAvailable',
    airConditioning: 'business.airConditioning',
    wheelchairAccessible: 'business.wheelchairAccessible',
    restroom: 'business.restroom',
    waitingArea: 'business.waitingArea',
    kidsZone: 'business.kidsZone',
    streetParking: 'business.streetParking',
    paidParking: 'business.paidParking',
    freeParking: 'business.freeParking',
    valetParking: 'business.valetParking',
    noParking: 'business.noParking',
    cashAccepted: 'business.cashAccepted',
    cardsAccepted: 'business.cardsAccepted',
    mobilePayments: 'business.mobilePayments',
    installments: 'business.installments',
    walkInsWelcome: 'business.walkInsWelcome',
    homeServices: 'business.homeServices',
    sameDayAppointments: 'business.sameDayAppointments',
    returnPolicy: 'business.returnPolicy',
    cancellationPolicy: 'business.cancellationPolicy',
    noShowPolicy: 'business.noShowPolicy',
    privacyPolicyShort: 'business.privacyPolicyShort',
    houseRules: 'business.houseRules',
    ageRequirements: 'business.ageRequirements',
    dressCode: 'business.dressCode',
    refundPolicy: 'business.refundPolicy',
    depositPolicy: 'business.depositPolicy',
  },
  professional: {
    portfolio: 'professional.portfolio',
    reels: 'professional.reels',
    pricing: 'professional.pricing',
    specialty: 'professional.specialty',
    specialties: 'professional.specialties',
    experienceYears: 'professional.experienceYears',
    nextAvailable: 'professional.nextAvailable',
    followers: 'professional.followers',
    verifiedWork: 'professional.verifiedWork',
    yearsExp: 'professional.yearsExp',
    certifications: 'professional.certifications',
    education: 'professional.education',
    awards: 'professional.awards',
    languagesSpoken: 'professional.languagesSpoken',
    aboutProfessional: 'professional.aboutProfessional',
    servicesBy: 'professional.servicesBy',
    bookWith: 'professional.bookWith',
    viewProfile: 'professional.viewProfile',
    workSamples: 'professional.workSamples',
    beforeAfter: 'professional.beforeAfter',
    customerReviews: 'professional.customerReviews',
    avgRating: 'professional.avgRating',
    totalBookings: 'professional.totalBookings',
    responseTime: 'professional.responseTime',
    withinHour: 'professional.withinHour',
    fewHours: 'professional.fewHours',
    sameDay: 'professional.sameDay',
    verifiedPro: 'professional.verifiedPro',
    topRatedPro: 'professional.topRatedPro',
    risingStar: 'professional.risingStar',
    elitePro: 'professional.elitePro',
  },
  filter: {
    title: 'filter.title',
    distance: 'filter.distance',
    price: 'filter.price',
    rating: 'filter.rating',
    reviews: 'filter.reviews',
    openNow: 'filter.openNow',
    availableNow: 'filter.availableNow',
    availableToday: 'filter.availableToday',
    category: 'filter.category',
    professional: 'filter.professional',
    homeService: 'filter.homeService',
    verified: 'filter.verified',
    promotion: 'filter.promotion',
    payment: 'filter.payment',
    parking: 'filter.parking',
    accessibility: 'filter.accessibility',
    earliestSlot: 'filter.earliestSlot',
    sortBy: 'filter.sortBy',
    nearest: 'filter.nearest',
    lowPrice: 'filter.lowPrice',
    highPrice: 'filter.highPrice',
    earliest: 'filter.earliest',
    trending: 'filter.trending',
    newest: 'filter.newest',
    topRated: 'filter.topRated',
    mostBooked: 'filter.mostBooked',
    recommended: 'filter.recommended',
    applyFilters: 'filter.applyFilters',
    resetFilters: 'filter.resetFilters',
    clearAll: 'filter.clearAll',
    filtersApplied: 'filter.filtersApplied',
    noResults: 'filter.noResults',
    expandFilters: 'filter.expandFilters',
    collapseFilters: 'filter.collapseFilters',
    genderPreference: 'filter.genderPreference',
    anyGender: 'filter.anyGender',
    femaleOnly: 'filter.femaleOnly',
    maleOnly: 'filter.maleOnly',
    nonBinary: 'filter.nonBinary',
    priceLevel: 'filter.priceLevel',
    budget: 'filter.budget',
    moderate: 'filter.moderate',
    premium: 'filter.premium',
    luxury: 'filter.luxury',
    duration: 'filter.duration',
    lessThan: 'filter.lessThan',
    moreThan: 'filter.moreThan',
    dateRange: 'filter.dateRange',
    timeOfDay: 'filter.timeOfDay',
    morning: 'filter.morning',
    afternoon: 'filter.afternoon',
    evening: 'filter.evening',
    anytime: 'filter.anytime',
    facilities: 'filter.facilities',
  },
  profile: {
    settings: 'profile.settings',
    theme: 'profile.theme',
    account: 'profile.account',
    privacy: 'profile.privacy',
    security: 'profile.security',
    language: 'profile.language',
    notifications: 'profile.notifications',
    nearby: 'profile.nearby',
    wallet: 'profile.wallet',
    loyalty: 'profile.loyalty',
    packages: 'profile.packages',
    memberships: 'profile.memberships',
    giftCards: 'profile.giftCards',
    support: 'profile.support',
    favorites: 'profile.favorites',
    following: 'profile.following',
    bookings: 'profile.bookings',
    upcoming: 'profile.upcoming',
    completed: 'profile.completed',
    cancelled: 'profile.cancelled',
    rebook: 'profile.rebook',
    reschedule: 'profile.reschedule',
    cancel: 'profile.cancel',
    review: 'profile.review',
    directions: 'profile.directions',
    editProfile: 'profile.editProfile',
    personalInfo: 'profile.personalInfo',
    profilePicture: 'profile.profilePicture',
    changePhoto: 'profile.changePhoto',
    removePhoto: 'profile.removePhoto',
    bio: 'profile.bio',
    aboutMe: 'profile.aboutMe',
    dateOfBirth: 'profile.dateOfBirth',
    gender: 'profile.gender',
    address: 'profile.address',
    city: 'profile.city',
    country: 'profile.country',
    postalCode: 'profile.postalCode',
    emailPreferences: 'profile.emailPreferences',
    pushPreferences: 'profile.pushPreferences',
    smsPreferences: 'profile.smsPreferences',
    marketingEmails: 'profile.marketingEmails',
    bookingEmails: 'profile.bookingEmails',
    reviewEmails: 'profile.reviewEmails',
    messageEmails: 'profile.messageEmails',
    systemEmails: 'profile.systemEmails',
    twoFactor: 'profile.twoFactor',
    changePassword: 'profile.changePassword',
    connectedDevices: 'profile.connectedDevices',
    loginHistory: 'profile.loginHistory',
    blockedUsers: 'profile.blockedUsers',
    deactivateAccount: 'profile.deactivateAccount',
    deleteAccount: 'profile.deleteAccount',
    becomePro: 'profile.becomePro',
    listBusiness: 'profile.listBusiness',
    inviteFriends: 'profile.inviteFriends',
    referralCode: 'profile.referralCode',
    referralLink: 'profile.referralLink',
    earnRewards: 'profile.earnRewards',
    balance: 'profile.balance',
    transactions: 'profile.transactions',
    addPaymentMethod: 'profile.addPaymentMethod',
    savedCards: 'profile.savedCards',
    redeemCode: 'profile.redeemCode',
    pointsBalance: 'profile.pointsBalance',
    currentTier: 'profile.currentTier',
    pointsToNextTier: 'profile.pointsToNextTier',
    tierBenefits: 'profile.tierBenefits',
    giftCardBalance: 'profile.giftCardBalance',
    buyGiftCard: 'profile.buyGiftCard',
    sendGiftCard: 'profile.sendGiftCard',
    contactSupport: 'profile.contactSupport',
    faq: 'profile.faq',
    reportIssue: 'profile.reportIssue',
    giveFeedback: 'profile.giveFeedback',
    rateApp: 'profile.rateApp',
    aboutLookiva: 'profile.aboutLookiva',
    appVersion: 'profile.appVersion',
    legal: 'profile.legal',
    darkMode: 'profile.darkMode',
    lightMode: 'profile.lightMode',
    systemDefault: 'profile.systemDefault',
    autoTranslate: 'profile.autoTranslate',
    reducedMotion: 'profile.reducedMotion',
    highContrast: 'profile.highContrast',
    largeText: 'profile.largeText',
    nearbyEnabled: 'profile.nearbyEnabled',
    nearbyRadius: 'profile.nearbyRadius',
    contentVisibility: 'profile.contentVisibility',
    showOnlineStatus: 'profile.showOnlineStatus',
    allowTags: 'profile.allowTags',
    publicProfile: 'profile.publicProfile',
    showBookings: 'profile.showBookings',
    showReviews: 'profile.showReviews',
    showFavorites: 'profile.showFavorites',
    showFollowing: 'profile.showFollowing',
  },
} as const;

export type I18nKeyType = typeof I18nKeys;

export function getLocaleMessages(locale: SupportedLocale): LocaleMessages {
  return locales[locale] ?? locales[defaultLocale];
}

export function normalizeLocale(locale: string | undefined | null): SupportedLocale {
  if (!locale) return defaultLocale;
  const lower = locale.toLowerCase().split('-')[0];
  if ((supportedLocales as readonly string[]).includes(lower)) {
    return lower as SupportedLocale;
  }
  return defaultLocale;
}

