'use client';

import * as React from 'react';
import Link from 'next/link';
import { useLocale, useTranslations } from 'next-intl';
import axios, { getAccessToken } from '@/lib/axios';
import { useCustomerRealtimeReload } from '@/lib/realtime';

const CONFIG: Record<string,{key:string;endpoint:string}> = {
  'profile':{key:'profile',endpoint:'/customer/profile'},
  'bookings':{key:'bookings',endpoint:'/customer-ops/bookings'},
  'favorites':{key:'favorites',endpoint:'/customer/favorites?limit=100'},
  'following':{key:'following',endpoint:'/customer/following?limit=100'},
  'notifications':{key:'notifications',endpoint:'/notifications?limit=100'},
  'chat':{key:'chat',endpoint:'/customer-ops/conversations'},
  'wallet':{key:'wallet',endpoint:'/customer-ops/retention'},
  'loyalty':{key:'loyalty',endpoint:'/customer-ops/retention'},
  'packages':{key:'packages',endpoint:'/customer-ops/retention'},
  'memberships':{key:'memberships',endpoint:'/customer-ops/retention'},
  'reviews':{key:'reviews',endpoint:'/customer-ops/reviews'},
  'settings':{key:'settings',endpoint:'/customer/preferences'},
  'security':{key:'security',endpoint:'/auth/sessions'},
  'nearby-settings':{key:'nearby-settings',endpoint:'/customer/preferences'},
};

function money(amount: unknown, currency = 'USD') {
  try { return new Intl.NumberFormat(undefined,{style:'currency',currency}).format(Number(amount ?? 0)); }
  catch { return `${Number(amount ?? 0).toLocaleString()} ${currency}`; }
}
function dateTime(value: unknown) { if(!value) return '—'; const d=new Date(String(value)); return Number.isNaN(d.getTime())?'—':d.toLocaleString(); }
function statusClass(status?: string) {
  const s=(status||'').toLowerCase();
  if(['completed','active','succeeded'].includes(s)) return 'bg-accent-green/10 text-accent-green';
  if(['cancelled','no_show','failed','revoked'].includes(s)) return 'bg-accent-red/10 text-accent-red';
  return 'bg-accent-gold-2/10 text-accent-gold-2';
}

export function AccountPage({section}:{section:string}){
  const locale=useLocale();
  const t=useTranslations('customerAccount');
  const cfg=CONFIG[section]||CONFIG.profile;
  const [data,setData]=React.useState<any>(null);
  const [loading,setLoading]=React.useState(true);
  const [error,setError]=React.useState('');
  const [notice,setNotice]=React.useState('');
  const [busy,setBusy]=React.useState('');

  async function load(){
    setLoading(true);setError('');
    try{const {data}=await axios.get(cfg.endpoint);setData(data);}catch(e){setError(e instanceof Error?e.message:t('loadError'));}finally{setLoading(false);}
  }
  React.useEffect(()=>{if(!getAccessToken()){setLoading(false);setError(t('signInRequired'));return;}void load();},[section]);
  useCustomerRealtimeReload(['booking:changed','notification:created','message:created','queue:changed'],()=>void load());

  async function mutate(key:string,request:()=>Promise<unknown>,message:string){
    setBusy(key);setError('');setNotice('');
    try{await request();setNotice(message);await load();}catch(e){setError(e instanceof Error?e.message:t('operationError'));}finally{setBusy('');}
  }

  const shell=(body:React.ReactNode)=><div className="mx-auto max-w-6xl px-4 py-8 md:px-6">
    <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-accent-gold-2">{t('eyebrow')}</p><h1 className="mt-2 text-3xl font-bold text-primary">{t(`sections.${cfg.key}.title`)}</h1><p className="mt-2 text-secondary">{t(`sections.${cfg.key}.subtitle`)}</p></div>{getAccessToken()&&<button onClick={()=>void load()} className="h-10 rounded-radius-md border border-border-subtle bg-surface-1 px-4 text-sm font-semibold text-primary">{t('refresh')}</button>}</div>
    {notice&&<div className="mt-5 rounded-radius-lg border border-accent-green/30 bg-accent-green/10 px-4 py-3 text-sm font-semibold text-accent-green">{notice}</div>}
    {loading&&<div className="mt-6 grid gap-3 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-28 animate-pulse rounded-radius-xl bg-surface-2"/>)}</div>}
    {error&&<div className="mt-6 rounded-radius-xl border border-accent-red/30 bg-accent-red/5 p-6"><p className="font-semibold text-primary">{error}</p>{!getAccessToken()?<Link href={`/${locale}/login`} className="mt-4 inline-flex rounded-radius-md bg-accent-gold-2 px-4 py-2 text-sm font-semibold text-surface-0">{t('signIn')}</Link>:<button onClick={()=>void load()} className="mt-4 rounded-radius-md bg-accent-gold-2 px-4 py-2 text-sm font-semibold text-surface-0">{t('retry')}</button>}</div>}
    {!loading&&!error&&body}
  </div>;

  if(section==='bookings') return shell(<div className="mt-6 grid gap-4">{Array.isArray(data)&&data.length?data.map((b:any)=><Link key={b.id} href={`/${locale}/bookings/${b.id}`} className="rounded-radius-xl border border-border-subtle bg-surface-1 p-5 hover:bg-surface-2"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-primary">{b.company?.display_name||t('labels.booking')}</p><p className="mt-1 text-sm text-secondary">{b.services?.map((s:any)=>s.service?.name).filter(Boolean).join(', ')||t('labels.service')}</p><p className="mt-1 text-xs text-muted">{dateTime(b.starts_at)} · {b.branch?.name||''}</p>{b.financial_snapshot&&<p className="mt-2 text-sm font-semibold text-primary">{money(b.financial_snapshot.grand_total,b.financial_snapshot.currency_code)}</p>}</div><span className={`rounded-radius-full px-3 py-1 text-xs font-semibold ${statusClass(b.status)}`}>{String(b.status).replaceAll('_',' ')}</span></div></Link>):<Empty title={t('nothingHere')} text={t('empty.bookings')}/>}</div>);

  if(section==='favorites') return shell(<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Array.isArray(data)&&data.length?data.map((f:any)=>{const e=f.entity||{};const type=f.favorite_type;const href=type==='company'?`/${locale}/businesses/${e.id}`:type==='professional'?`/${locale}/professionals/${e.id}`:type==='service'?`/${locale}/services/${e.id}`:`/${locale}/discover`;return <article key={f.id} className="rounded-radius-xl border border-border-subtle bg-surface-1 p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted">{String(type||'favorite')}</p><Link href={href} className="mt-2 block text-lg font-semibold text-primary hover:text-accent-gold-2">{e.display_name||e.name||e.user?.full_name||t('labels.savedItem')}</Link><button disabled={busy===f.id} onClick={()=>void mutate(f.id,()=>axios.delete(`/customer/favorites/${f.id}`),t('messages.favoriteRemoved'))} className="mt-4 text-sm font-semibold text-accent-red">{busy===f.id?t('actions.removing'):t('actions.remove')}</button></article>}):<Empty title={t('nothingHere')} text={t('empty.favorites')}/>}</div>);

  if(section==='following') return shell(<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Array.isArray(data)&&data.length?data.map((f:any)=>{const e=f.target||{};const type=f.target_type;const href=type==='professional'?`/${locale}/professionals/${e.id}`:`/${locale}/businesses/${e.id}`;return <article key={f.id} className="rounded-radius-xl border border-border-subtle bg-surface-1 p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted">{type}</p><Link href={href} className="mt-2 block text-lg font-semibold text-primary hover:text-accent-gold-2">{e.display_name||e.user?.full_name||t('labels.followedProfile')}</Link><button disabled={busy===f.id} onClick={()=>void mutate(f.id,()=>axios.delete(`/customer/following/${f.id}`),t('messages.unfollowed'))} className="mt-4 text-sm font-semibold text-accent-red">{busy===f.id?t('actions.saving'):t('actions.unfollow')}</button></article>}):<Empty title={t('nothingHere')} text={t('empty.following')}/>}</div>);

  if(section==='notifications') {const items=Array.isArray(data?.items)?data.items:[];return shell(<div className="mt-6 space-y-3"><div className="flex justify-end"><button disabled={!!busy||!items.some((n:any)=>!n.read_at)} onClick={()=>void mutate('read-all',()=>axios.patch('/notifications/read-all'),t('messages.allRead'))} className="text-sm font-semibold text-accent-gold-2 disabled:opacity-50">{t('actions.markAllRead')}</button></div>{items.length?items.map((n:any)=><button key={n.id} onClick={()=>!n.read_at&&void mutate(n.id,()=>axios.patch(`/notifications/${n.id}/read`),t('messages.notificationRead'))} className={`block w-full rounded-radius-xl border p-5 text-left ${n.read_at?'border-border-subtle bg-surface-1':'border-accent-gold-2/30 bg-accent-gold-2/5'}`}><div className="flex justify-between gap-4"><div><p className="font-semibold text-primary">{n.title}</p><p className="mt-1 text-sm text-secondary">{n.body}</p><p className="mt-2 text-xs text-muted">{dateTime(n.created_at)}</p></div>{!n.read_at&&<span className="h-2.5 w-2.5 rounded-full bg-accent-gold-2"/>}</div></button>):<Empty title={t('nothingHere')} text={t('empty.notifications')}/>}</div>);}

  if(section==='chat') return shell(<div className="mt-6 space-y-3">{Array.isArray(data)&&data.length?data.map((c:any)=>{const last=c.messages?.[0];const others=(c.members||[]).filter((m:any)=>m.user).map((m:any)=>m.user.full_name).filter(Boolean).join(', ');return <Link key={c.id} href={`/${locale}/chat/${c.id}`} className="block rounded-radius-xl border border-border-subtle bg-surface-1 p-5 hover:bg-surface-2"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-primary">{c.title||others||t('labels.conversation')}</p><p className="mt-1 line-clamp-2 text-sm text-secondary">{last?.body_plain||t('labels.noMessages')}</p></div><span className="text-xs text-muted">{dateTime(last?.created_at||c.updated_at)}</span></div></Link>}):<Empty title={t('nothingHere')} text={t('labels.noConversations')}/>}</div>);

  if(['wallet','loyalty','packages','memberships'].includes(section)) {const source=data||{}; if(section==='wallet'){const w=source.wallet;return shell(<div className="mt-6 space-y-4"><div className="rounded-radius-2xl border border-accent-gold-2/30 bg-surface-1 p-6"><p className="text-sm text-muted">{t('labels.walletBalance')}</p><p className="mt-2 text-4xl font-bold text-primary">{w?money(w.balance,w.currency_code):'—'}</p></div><Ledger rows={w?.ledger||[]} title={t('labels.recentActivity')} empty={t('empty.activity')} transaction={t('labels.transaction')}/></div>);} if(section==='loyalty'){const l=source.loyalty;return shell(<div className="mt-6 space-y-4"><div className="rounded-radius-2xl border border-border-subtle bg-surface-1 p-6"><p className="text-sm text-muted">{t('labels.loyaltyPoints')}</p><p className="mt-2 text-4xl font-bold text-primary">{Number(l?.points_balance||0).toLocaleString()}</p><p className="mt-2 text-sm text-secondary">{t('labels.tier')}: {l?.tier||t('labels.standard')}</p></div><Ledger rows={l?.ledger||[]} title={t('labels.recentActivity')} empty={t('empty.activity')} transaction={t('labels.transaction')}/></div>);} const list=section==='packages'?source.packages:source.memberships; return shell(<div className="mt-6 grid gap-4 md:grid-cols-2">{Array.isArray(list)&&list.length?list.map((item:any)=><article key={item.id} className="rounded-radius-xl border border-border-subtle bg-surface-1 p-5"><p className="text-lg font-semibold text-primary">{item.package?.name||item.membership?.name||section}</p><p className="mt-2 text-sm text-secondary">{t('labels.status')}: {item.status||t('labels.active')}</p><p className="mt-1 text-xs text-muted">{item.expires_at?`${t('labels.expires')} ${dateTime(item.expires_at)}`:item.current_period_end?`${t('labels.renews')} ${dateTime(item.current_period_end)}`:t('labels.noExpiry')}</p></article>):<Empty title={t('nothingHere')} text={t('empty.generic')}/>}</div>);}

  if(section==='reviews') return shell(<div className="mt-6 grid gap-4 md:grid-cols-2">{Array.isArray(data)&&data.length?data.map((r:any)=><article key={r.id} className="rounded-radius-xl border border-border-subtle bg-surface-1 p-5"><div className="flex items-center justify-between"><p className="font-semibold text-primary">{r.company?.display_name||r.professional?.display_name||r.service?.name||t('labels.review')}</p><span className="font-semibold text-accent-gold-2">★ {Number(r.overall_rating||0).toFixed(1)}</span></div><p className="mt-3 text-sm text-secondary">{r.body||t('labels.noComment')}</p><p className="mt-3 text-xs text-muted">{r.is_verified?t('labels.verifiedAppointment'):t('labels.review')} · {dateTime(r.created_at)}</p></article>):<Empty title={t('nothingHere')} text={t('empty.reviews')}/>}</div>);

  if(section==='security') {const sessions=Array.isArray(data?.sessions)?data.sessions:[];return shell(<div className="mt-6 space-y-3">{sessions.length?sessions.map((s:any)=><article key={s.id} className="flex flex-col gap-3 rounded-radius-xl border border-border-subtle bg-surface-1 p-5 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold text-primary">{s.deviceName||s.deviceType||t('labels.deviceSession')}</p><p className="mt-1 text-sm text-secondary">{s.city||t('labels.unknownLocation')} · {s.ipAddress||t('labels.ipUnavailable')}</p><p className="mt-1 text-xs text-muted">{t('labels.lastActive')} {dateTime(s.lastActiveAt)} · {t('labels.expires')} {dateTime(s.expiresAt)}</p></div><button disabled={busy===s.id||!!s.revokedAt} onClick={()=>void mutate(s.id,()=>axios.delete(`/auth/sessions/${s.id}`),t('messages.sessionRevoked'))} className="text-sm font-semibold text-accent-red disabled:opacity-50">{s.revokedAt?t('actions.revoke'):busy===s.id?t('actions.revoking'):t('actions.revoke')}</button></article>):<Empty title={t('nothingHere')} text={t('empty.sessions')}/>}</div>);}

  if(section==='settings') {const up=data?.user_preferences||{};return shell(<form className="mt-6 grid gap-4 rounded-radius-xl border border-border-subtle bg-surface-1 p-6 md:grid-cols-2" onSubmit={(e)=>{e.preventDefault();const fd=new FormData(e.currentTarget);void mutate('prefs',()=>axios.put('/customer/preferences',{user_preferences:{auto_translate:fd.get('auto_translate')==='on',reduced_motion:fd.get('reduced_motion')==='on',high_contrast:fd.get('high_contrast')==='on',show_verified_only:fd.get('show_verified_only')==='on'}}),t('messages.preferencesSaved'))}}>{[['auto_translate',t('labels.autoTranslate'),up.auto_translate],['reduced_motion',t('labels.reduceMotion'),up.reduced_motion],['high_contrast',t('labels.highContrast'),up.high_contrast],['show_verified_only',t('labels.showVerifiedOnly'),up.show_verified_only]].map(([name,label,checked])=><label key={String(name)} className="flex items-center gap-3 rounded-radius-lg bg-surface-2 p-4"><input name={String(name)} type="checkbox" defaultChecked={Boolean(checked)} className="h-4 w-4 accent-accent-gold-2"/><span className="text-sm font-medium text-primary">{String(label)}</span></label>)}<button disabled={busy==='prefs'} className="h-11 rounded-radius-md bg-accent-gold-2 px-5 font-semibold text-surface-0 md:col-span-2 md:justify-self-start">{busy==='prefs'?t('actions.saving'):t('actions.savePreferences')}</button></form>);}

  if(section==='nearby-settings') {const np=data?.nearby_notification_preferences||{};return shell(<form className="mt-6 grid gap-4 rounded-radius-xl border border-border-subtle bg-surface-1 p-6 md:grid-cols-2" onSubmit={(e)=>{e.preventDefault();const fd=new FormData(e.currentTarget);void mutate('nearby',()=>axios.put('/customer/preferences',{nearby_notification_preferences:{enabled:fd.get('enabled')==='on',distance_threshold_meters:Number(fd.get('distance')||500),min_rating:fd.get('min_rating')?Number(fd.get('min_rating')):null,include_offers:fd.get('include_offers')==='on',include_availability:fd.get('include_availability')==='on',daily_max_notifications:Number(fd.get('daily_max')||2),quiet_hours_start:String(fd.get('quiet_start')||'')||null,quiet_hours_end:String(fd.get('quiet_end')||'')||null}}),t('messages.nearbySaved'))}}><label className="flex items-center gap-3 rounded-radius-lg bg-surface-2 p-4 md:col-span-2"><input name="enabled" type="checkbox" defaultChecked={Boolean(np.enabled)} className="h-4 w-4 accent-accent-gold-2"/><span className="font-semibold text-primary">{t('labels.enableNearby')}</span></label><Field label={t('labels.distanceMeters')}><input name="distance" type="number" min="100" max="100000" defaultValue={np.distance_threshold_meters??500} className="input"/></Field><Field label={t('labels.minimumRating')}><input name="min_rating" type="number" min="0" max="5" step="0.1" defaultValue={np.min_rating??''} className="input"/></Field><Field label={t('labels.maxAlertsDay')}><input name="daily_max" type="number" min="0" max="50" defaultValue={np.daily_max_notifications??2} className="input"/></Field><div className="grid grid-cols-2 gap-2"><Field label={t('labels.quietStart')}><input name="quiet_start" type="time" defaultValue={np.quiet_hours_start??''} className="input"/></Field><Field label={t('labels.quietEnd')}><input name="quiet_end" type="time" defaultValue={np.quiet_hours_end??''} className="input"/></Field></div>{[['include_offers',t('labels.nearbyOffers'),np.include_offers],['include_availability',t('labels.availableNowAlerts'),np.include_availability]].map(([name,label,checked])=><label key={String(name)} className="flex items-center gap-3 rounded-radius-lg bg-surface-2 p-4"><input name={String(name)} type="checkbox" defaultChecked={checked!==false} className="h-4 w-4 accent-accent-gold-2"/><span className="text-sm text-primary">{String(label)}</span></label>)}<button disabled={busy==='nearby'} className="h-11 rounded-radius-md bg-accent-gold-2 px-5 font-semibold text-surface-0 md:col-span-2 md:justify-self-start">{busy==='nearby'?t('actions.saving'):t('actions.saveNearby')}</button></form>);}

  if(section==='profile') {const profile=data?.user_profiles?.[0]||{};return shell(<div className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><form className="grid gap-4 rounded-radius-xl border border-border-subtle bg-surface-1 p-6 sm:grid-cols-2" onSubmit={(e)=>{e.preventDefault();const fd=new FormData(e.currentTarget);void mutate('profile',()=>axios.patch('/customer/profile',{firstName:String(fd.get('firstName')||''),lastName:String(fd.get('lastName')||''),bio:String(fd.get('bio')||'')||null,locale:String(fd.get('locale')||'en'),themeMode:String(fd.get('themeMode')||'midnight-gold')}),t('messages.profileSaved'))}}><Field label={t('labels.firstName')}><input name="firstName" required defaultValue={profile.first_name||data?.full_name?.split(' ')?.[0]||''} className="input"/></Field><Field label={t('labels.lastName')}><input name="lastName" required defaultValue={profile.last_name||data?.full_name?.split(' ')?.slice(1).join(' ')||''} className="input"/></Field><Field label={t('labels.language')}><select name="locale" defaultValue={data?.locale||locale} className="input"><option value="en">English</option><option value="ar">العربية</option><option value="fr">Français</option></select></Field><Field label={t('labels.appearance')}><select name="themeMode" defaultValue={data?.theme_mode||'midnight-gold'} className="input"><option value="midnight-gold">{t('labels.midnightGold')}</option><option value="silver-light">{t('labels.silverLight')}</option><option value="system">{t('labels.system')}</option></select></Field><label className="sm:col-span-2"><span className="mb-1.5 block text-sm font-medium text-secondary">{t('labels.bio')}</span><textarea name="bio" rows={4} defaultValue={profile.bio||''} className="input h-auto py-3"/></label><button disabled={busy==='profile'} className="h-11 rounded-radius-md bg-accent-gold-2 px-5 font-semibold text-surface-0 sm:col-span-2 sm:justify-self-start">{busy==='profile'?t('actions.saving'):t('actions.saveProfile')}</button></form><nav className="rounded-radius-xl border border-border-subtle bg-surface-1 p-5"><p className="font-semibold text-primary">{t('labels.accountShortcuts')}</p><div className="mt-4 grid gap-2">{[['bookings',t('sections.bookings.title')],['favorites',t('sections.favorites.title')],['following',t('sections.following.title')],['wallet',t('sections.wallet.title')],['notifications',t('sections.notifications.title')],['security',t('sections.security.title')],['nearby-settings',t('sections.nearby-settings.title')]].map(([href,label])=><Link key={href} href={`/${locale}/${href}`} className="rounded-radius-md bg-surface-2 px-4 py-3 text-sm font-medium text-primary hover:text-accent-gold-2">{label}</Link>)}</div></nav></div>);}

  return shell(<Empty title={t('nothingHere')} text={t('empty.generic')}/>);
}

function Empty({title,text}:{title:string;text:string}){return <div className="col-span-full rounded-radius-xl border border-border-subtle bg-surface-1 p-10 text-center"><h2 className="font-semibold text-primary">{title}</h2><p className="mt-2 text-sm text-muted">{text}</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1.5 block text-sm font-medium text-secondary">{label}</span>{children}</label>}
function Ledger({rows,title,empty,transaction}:{rows:any[];title:string;empty:string;transaction:string}){return <div className="rounded-radius-xl border border-border-subtle bg-surface-1 p-5"><h2 className="font-semibold text-primary">{title}</h2><div className="mt-3 divide-y divide-border-subtle">{rows.length?rows.map((r:any)=><div key={r.id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-medium text-primary">{r.description||r.entry_type||r.transaction_type||transaction}</p><p className="text-xs text-muted">{dateTime(r.created_at)}</p></div><p className="text-sm font-semibold text-primary">{Number(r.amount||r.points||0).toLocaleString()}</p></div>):<p className="py-4 text-sm text-muted">{empty}</p>}</div></div>}
