#!/usr/bin/env python3
from __future__ import annotations
import hashlib, re, shutil
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SCHEMA=ROOT/'apps/api/prisma/schema.prisma'
OUT_DIR=ROOT/'apps/api/prisma/migrations/202609300001_baseline'
SCALAR={'String','Int','Float','Boolean','DateTime','Json','Bytes','Decimal','BigInt'}

def safe_name(prefix:str,*parts:str)->str:
    raw='_'.join([prefix,*parts])
    if len(raw)<=60:return raw
    return raw[:48]+'_'+hashlib.sha1(raw.encode()).hexdigest()[:10]

def parse_schema(text:str):
    models=[]
    for m in re.finditer(r'^model\s+(\w+)\s*\{\n(.*?)^\}', text, re.M|re.S):
        name,body=m.group(1),m.group(2)
        table=name
        mm=re.search(r'@@map\("([^"]+)"\)',body)
        if mm: table=mm.group(1)
        fields=[]; attrs=[]; relations=[]
        for raw in body.splitlines():
            line=raw.strip()
            if not line or line.startswith('//'): continue
            if line.startswith('@@'):
                attrs.append(line); continue
            parts=line.split(None,2)
            if len(parts)<2: continue
            fname,ftype=parts[0],parts[1]
            tail=parts[2] if len(parts)>2 else ''
            optional=ftype.endswith('?'); array=ftype.endswith('[]')
            base=ftype[:-1] if optional else ftype
            base=base[:-2] if base.endswith('[]') else base
            is_unsupported=base.startswith('Unsupported(')
            if base in SCALAR or is_unsupported:
                fmap=re.search(r'@map\("([^"]+)"\)',tail)
                fields.append({'name':fname,'column':fmap.group(1) if fmap else fname,'type':base,'optional':optional,'array':array,'tail':tail})
            if '@relation(' in tail:
                fm=re.search(r'fields:\s*\[([^\]]+)\]',tail); rm=re.search(r'references:\s*\[([^\]]+)\]',tail)
                if fm and rm:
                    ondelete=re.search(r'onDelete:\s*(\w+)',tail)
                    relations.append({'target_model':base.rstrip('?'), 'fields':[x.strip() for x in fm.group(1).split(',')], 'refs':[x.strip() for x in rm.group(1).split(',')], 'ondelete':ondelete.group(1) if ondelete else None})
        models.append({'name':name,'table':table,'body':body,'fields':fields,'attrs':attrs,'relations':relations})
    return models

def sql_type(f):
    if f['type'].startswith('Unsupported('):
        inner=re.search(r'Unsupported\("(.+)"\)',f['type'])
        typ=inner.group(1) if inner else 'TEXT'
    else:
        typ={'String':'TEXT','Int':'INTEGER','Float':'DOUBLE PRECISION','Boolean':'BOOLEAN','DateTime':'TIMESTAMP(3)','Json':'JSONB','Bytes':'BYTEA','Decimal':'DECIMAL','BigInt':'BIGINT'}[f['type']]
    if f['array']: typ += '[]'
    return typ

def default_sql(f):
    tail=f['tail']
    if '@default(cuid())' in tail or '@default(uuid())' in tail: return '' # Prisma creates application ids
    if '@default(now())' in tail: return ' DEFAULT CURRENT_TIMESTAMP'
    if '@default(autoincrement())' in tail: return ' GENERATED BY DEFAULT AS IDENTITY'
    if '@default([])' in tail:
        base=sql_type({**f,'array':False})
        return f" DEFAULT ARRAY[]::{base}[]"
    m=re.search(r'@default\(\"((?:\\.|[^\"])*)\"\)',tail)
    if m: return " DEFAULT '"+m.group(1).replace("'","''")+"'"
    m=re.search(r'@default\((-?\d+(?:\.\d+)?|true|false)\)',tail)
    if m: return ' DEFAULT '+m.group(1)
    return ''

def main():
    models=parse_schema(SCHEMA.read_text())
    model_by={m['name']:m for m in models}
    lines=['-- LOOKIVA schema-aligned baseline migration','-- Generated from prisma/schema.prisma. Fresh databases only.','CREATE EXTENSION IF NOT EXISTS postgis;','CREATE EXTENSION IF NOT EXISTS btree_gist;','']
    field_maps={m['name']:{f['name']:f['column'] for f in m['fields']} for m in models}
    for m in models:
        cols=[]
        for f in m['fields']:
            bits=f'  "{f["column"]}" {sql_type(f)}'
            if '@id' in f['tail']: bits+=' PRIMARY KEY'
            if not f['optional']: bits+=' NOT NULL'
            bits+=default_sql(f)
            if '@unique' in f['tail']: bits+=' UNIQUE'
            cols.append(bits)
        lines += [f'CREATE TABLE "{m["table"]}" (',',\n'.join(cols),');','']
    # Foreign keys only after all tables exist.
    for m in models:
        for r in m['relations']:
            target=model_by.get(r['target_model'])
            if not target: continue
            lcols=[field_maps[m['name']].get(x,x) for x in r['fields']]
            rcols=[field_maps[target['name']].get(x,x) for x in r['refs']]
            name=safe_name('fk',m['table'],*lcols,target['table'])
            action={'Cascade':'CASCADE','SetNull':'SET NULL','Restrict':'RESTRICT','NoAction':'NO ACTION','SetDefault':'SET DEFAULT'}.get(r['ondelete'] or '','NO ACTION')
            lines.append(f'ALTER TABLE "{m["table"]}" ADD CONSTRAINT "{name}" FOREIGN KEY ({", ".join(chr(34)+x+chr(34) for x in lcols)}) REFERENCES "{target["table"]}" ({", ".join(chr(34)+x+chr(34) for x in rcols)}) ON DELETE {action};')
    lines.append('')
    # Model and field indexes / unique composites.
    for m in models:
        fmap=field_maps[m['name']]
        for f in m['fields']:
            if '@unique' in f['tail'] or '@id' in f['tail']: continue
            # no implicit indexes for ordinary fields
        for attr in m['attrs']:
            kind=None
            if attr.startswith('@@index'):kind='INDEX'
            elif attr.startswith('@@unique'):kind='UNIQUE INDEX'
            else: continue
            mm=re.search(r'\[([^\]]+)\]',attr)
            if not mm: continue
            rawfields=[]
            for token in mm.group(1).split(','):
                token=token.strip().split('(')[0].strip()
                if token: rawfields.append(token)
            cols=[fmap.get(x,x) for x in rawfields]
            if not cols: continue
            name=safe_name('uidx' if kind.startswith('UNIQUE') else 'idx',m['table'],*cols)
            lines.append(f'CREATE {kind} "{name}" ON "{m["table"]}" ({", ".join(chr(34)+x+chr(34) for x in cols)});')
    lines += ['', '-- Database-level overlap guards. Application SERIALIZABLE transactions remain in place as a second layer.']
    lines += [r'''
CREATE OR REPLACE FUNCTION lookiva_guard_professional_overlap() RETURNS trigger AS $$
DECLARE v_start TIMESTAMP(3); v_end TIMESTAMP(3); v_status TEXT;
BEGIN
  SELECT starts_at, ends_at, status INTO v_start, v_end, v_status FROM appointments WHERE id = NEW.appointment_id;
  IF v_status IN ('pending','confirmed','checked_in','in_progress') AND v_start IS NOT NULL AND v_end IS NOT NULL AND EXISTS (
    SELECT 1 FROM appointment_participants ap JOIN appointments a ON a.id=ap.appointment_id
    WHERE ap.professional_id=NEW.professional_id AND ap.id<>NEW.id
      AND a.status IN ('pending','confirmed','checked_in','in_progress')
      AND a.starts_at < v_end AND a.ends_at > v_start
  ) THEN RAISE EXCEPTION 'Professional booking overlap'; END IF;
  RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER trg_guard_professional_overlap BEFORE INSERT OR UPDATE ON appointment_participants
FOR EACH ROW EXECUTE FUNCTION lookiva_guard_professional_overlap();

CREATE OR REPLACE FUNCTION lookiva_guard_resource_overlap() RETURNS trigger AS $$
DECLARE v_start TIMESTAMP(3); v_end TIMESTAMP(3); v_status TEXT;
BEGIN
  SELECT COALESCE(NEW.starts_at,starts_at), COALESCE(NEW.ends_at,ends_at), status INTO v_start, v_end, v_status FROM appointments WHERE id = NEW.appointment_id;
  IF v_status IN ('pending','confirmed','checked_in','in_progress') AND v_start IS NOT NULL AND v_end IS NOT NULL AND EXISTS (
    SELECT 1 FROM appointment_resources ar JOIN appointments a ON a.id=ar.appointment_id
    WHERE ar.resource_id=NEW.resource_id AND ar.id<>NEW.id
      AND a.status IN ('pending','confirmed','checked_in','in_progress')
      AND COALESCE(ar.starts_at,a.starts_at) < v_end AND COALESCE(ar.ends_at,a.ends_at) > v_start
  ) THEN RAISE EXCEPTION 'Resource booking overlap'; END IF;
  RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER trg_guard_resource_overlap BEFORE INSERT OR UPDATE ON appointment_resources
FOR EACH ROW EXECUTE FUNCTION lookiva_guard_resource_overlap();

CREATE OR REPLACE FUNCTION lookiva_guard_appointment_reschedule() RETURNS trigger AS $$
BEGIN
  IF NEW.status IN ('pending','confirmed','checked_in','in_progress') AND (NEW.starts_at IS DISTINCT FROM OLD.starts_at OR NEW.ends_at IS DISTINCT FROM OLD.ends_at OR NEW.status IS DISTINCT FROM OLD.status) THEN
    IF EXISTS (
      SELECT 1 FROM appointment_participants mine JOIN appointment_participants other ON other.professional_id=mine.professional_id AND other.appointment_id<>NEW.id
      JOIN appointments a ON a.id=other.appointment_id
      WHERE mine.appointment_id=NEW.id AND a.status IN ('pending','confirmed','checked_in','in_progress') AND a.starts_at<NEW.ends_at AND a.ends_at>NEW.starts_at
    ) THEN RAISE EXCEPTION 'Professional booking overlap after reschedule'; END IF;
    IF EXISTS (
      SELECT 1 FROM appointment_resources mine JOIN appointment_resources other ON other.resource_id=mine.resource_id AND other.appointment_id<>NEW.id
      JOIN appointments a ON a.id=other.appointment_id
      WHERE mine.appointment_id=NEW.id AND a.status IN ('pending','confirmed','checked_in','in_progress')
        AND COALESCE(other.starts_at,a.starts_at)<NEW.ends_at AND COALESCE(other.ends_at,a.ends_at)>NEW.starts_at
    ) THEN RAISE EXCEPTION 'Resource booking overlap after reschedule'; END IF;
  END IF;
  RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER trg_guard_appointment_reschedule BEFORE UPDATE OF starts_at, ends_at, status ON appointments
FOR EACH ROW EXECUTE FUNCTION lookiva_guard_appointment_reschedule();
''']
    OUT_DIR.mkdir(parents=True,exist_ok=True)
    (OUT_DIR/'migration.sql').write_text('\n'.join(lines)+'\n')
    # Archive legacy hand-written migrations so Prisma will not apply incompatible DDL.
    legacy=ROOT/'apps/api/prisma/legacy_migrations_incompatible'
    legacy.mkdir(exist_ok=True)
    migroot=ROOT/'apps/api/prisma/migrations'
    for d in list(migroot.iterdir()):
        if d.is_dir() and d.name!='202609300001_baseline':
            dest=legacy/d.name
            if dest.exists(): shutil.rmtree(dest)
            shutil.move(str(d),str(dest))
    print(f'Generated {len(models)} tables at {OUT_DIR}/migration.sql')

if __name__=='__main__': main()
