import 'package:flutter/material.dart';

const _strings = <String, Map<String, String>>{
  'en': {
    'splashTagline':'Dashboard for pros & owners','business':'BUSINESS','signIn':'Business Sign In','signInBody':'Secure access for owners, managers, receptionists and professionals.','emailPhone':'Email or phone','password':'Password','keepSignedIn':'Keep me signed in','signingIn':'Signing in…','loginMissing':'Enter your email/phone and password.','apiConfigured':'API URL is configured at build time for production.',
    'setup':'Business Setup','onboarding':'Business Onboarding','onboardingBody':'Set locations, services, staff, payout, tax, and compliance basics.','continue':'Continue',
    'dashboard':'Dashboard','calendar':'Calendar','floor':'Floor','clients':'Clients','more':'More','theme':'Theme','language':'Language','notifications':'Notifications',
    'operations':'Operations','operationsBody':'Live company data. Access is limited by your assigned role and branch scope.','services':'Services','professionals':'Professionals','staff':'Staff & permissions','payments':'Payments','finance':'Finance reconciliation','analytics':'Analytics','queue':'Walk-in queue','promotions':'Promotions','inventory':'Inventory','commissions':'Commissions','forms':'Consent forms','reviews':'Reviews','branches':'Branches','subscription':'Subscription','audit':'Audit log','signOut':'Sign out','retry':'Retry','noRecords':'No records yet','overview':'Business Overview','appointments':'Appointments','liveFloor':'Live Floor & Resources','customers':'Customers','details':'Details','item':'Item','items':'items','unableLoad':'Unable to load','scanCheckInQr':'Scan check-in QR','scanQrHint':'Scan the customer\'s signed booking QR when they arrive.','checkInSuccess':'Customer checked in successfully','scanAnother':'Scan another','toggleTorch':'Toggle flashlight','switchCamera':'Switch camera','cameraUnavailable':'Camera is unavailable or permission was denied','payouts':'Payouts','addCommission':'Add commission','createPayout':'Create payout','standardCommission':'Standard commission','ruleName':'Rule name','professional':'Professional','allProfessionals':'All professionals','commissionType':'Commission type','percentage':'Percentage','fixedAmount':'Fixed amount','commissionValue':'Rate / amount','cancel':'Cancel','save':'Save','commissionCreated':'Commission rule created','noProfessionals':'No active professionals found','periodStart':'Period start','periodEnd':'Period end','reference':'Reference','markPaid':'Mark as paid now','payoutCreated':'Payout created','customer':'Customer','recentAppointments':'Recent appointments','appointment':'Appointment','recentPayments':'Recent payments','noBranches':'No active branches found','branch':'Branch','schedule':'Schedule','start':'Start','end':'End','scheduleSaved':'Schedule saved','commission':'Commission','commissionUpdated':'Commission updated','editService':'Edit service','serviceName':'Service name','durationMinutes':'Duration minutes','price':'Price','depositPercent':'Deposit %','serviceUpdated':'Service updated'
  },
  'ar': {
    'splashTagline':'لوحة تحكم للمحترفين والمالكين','business':'الأعمال','signIn':'تسجيل دخول الأعمال','signInBody':'دخول آمن للمالكين والمديرين وموظفي الاستقبال والمحترفين.','emailPhone':'البريد أو الهاتف','password':'كلمة المرور','keepSignedIn':'ابقني مسجلاً','signingIn':'جارٍ تسجيل الدخول…','loginMissing':'أدخل البريد/الهاتف وكلمة المرور.','apiConfigured':'عنوان API يتم ضبطه وقت بناء نسخة الإنتاج.',
    'setup':'إعداد المنشأة','onboarding':'تهيئة المنشأة','onboardingBody':'اضبط المواقع والخدمات والموظفين والمدفوعات والضرائب ومتطلبات الامتثال.','continue':'متابعة',
    'dashboard':'لوحة التحكم','calendar':'التقويم','floor':'الصالة','clients':'العملاء','more':'المزيد','theme':'المظهر','language':'اللغة','notifications':'الإشعارات',
    'operations':'العمليات','operationsBody':'بيانات حية للمنشأة. الوصول محدود حسب الدور والفرع المعيّن.','services':'الخدمات','professionals':'المحترفون','staff':'الموظفون والصلاحيات','payments':'المدفوعات','finance':'المطابقة المالية','analytics':'التحليلات','queue':'طابور الدخول','promotions':'العروض','inventory':'المخزون','commissions':'العمولات','forms':'نماذج الموافقة','reviews':'التقييمات','branches':'الفروع','subscription':'الاشتراك','audit':'سجل التدقيق','signOut':'تسجيل الخروج','retry':'إعادة المحاولة','noRecords':'لا توجد سجلات بعد','overview':'نظرة عامة','appointments':'المواعيد','liveFloor':'الصالة والموارد مباشرة','customers':'العملاء','details':'التفاصيل','item':'عنصر','items':'عناصر','unableLoad':'تعذر التحميل','scanCheckInQr':'مسح رمز QR لتسجيل الوصول','scanQrHint':'امسح رمز الحجز الموقّع للعميل عند وصوله.','checkInSuccess':'تم تسجيل وصول العميل بنجاح','scanAnother':'مسح رمز آخر','toggleTorch':'تشغيل أو إطفاء الفلاش','switchCamera':'تبديل الكاميرا','cameraUnavailable':'الكاميرا غير متاحة أو تم رفض الإذن','payouts':'الدفعات','addCommission':'إضافة عمولة','createPayout':'إنشاء دفعة','standardCommission':'عمولة قياسية','ruleName':'اسم القاعدة','professional':'المحترف','allProfessionals':'كل المحترفين','commissionType':'نوع العمولة','percentage':'نسبة مئوية','fixedAmount':'مبلغ ثابت','commissionValue':'النسبة / المبلغ','cancel':'إلغاء','save':'حفظ','commissionCreated':'تم إنشاء قاعدة العمولة','noProfessionals':'لا يوجد محترفون نشطون','periodStart':'بداية الفترة','periodEnd':'نهاية الفترة','reference':'المرجع','markPaid':'تحديد كمدفوع الآن','payoutCreated':'تم إنشاء الدفعة','customer':'العميل','recentAppointments':'المواعيد الأخيرة','appointment':'موعد','recentPayments':'المدفوعات الأخيرة','noBranches':'لا توجد فروع نشطة','branch':'الفرع','schedule':'الجدول','start':'البداية','end':'النهاية','scheduleSaved':'تم حفظ الجدول','commission':'العمولة','commissionUpdated':'تم تحديث العمولة','editService':'تعديل الخدمة','serviceName':'اسم الخدمة','durationMinutes':'مدة الخدمة بالدقائق','price':'السعر','depositPercent':'نسبة العربون','serviceUpdated':'تم تحديث الخدمة'
  },
  'fr': {
    'splashTagline':'Tableau de bord pour pros et propriétaires','business':'ENTREPRISE','signIn':'Connexion entreprise','signInBody':'Accès sécurisé pour propriétaires, managers, réceptionnistes et professionnels.','emailPhone':'E-mail ou téléphone','password':'Mot de passe','keepSignedIn':'Rester connecté','signingIn':'Connexion…','loginMissing':'Saisissez votre e-mail/téléphone et votre mot de passe.','apiConfigured':'L’URL API est configurée lors du build de production.',
    'setup':'Configuration entreprise','onboarding':'Démarrage entreprise','onboardingBody':'Configurez les lieux, services, équipes, paiements, taxes et exigences de conformité.','continue':'Continuer',
    'dashboard':'Tableau de bord','calendar':'Calendrier','floor':'Salle','clients':'Clients','more':'Plus','theme':'Thème','language':'Langue','notifications':'Notifications',
    'operations':'Opérations','operationsBody':'Données en direct. L’accès est limité par votre rôle et votre succursale.','services':'Services','professionals':'Professionnels','staff':'Équipe et permissions','payments':'Paiements','finance':'Rapprochement financier','analytics':'Analyses','queue':'File sans rendez-vous','promotions':'Promotions','inventory':'Stock','commissions':'Commissions','forms':'Formulaires de consentement','reviews':'Avis','branches':'Succursales','subscription':'Abonnement','audit':'Journal d’audit','signOut':'Se déconnecter','retry':'Réessayer','noRecords':'Aucun enregistrement','overview':'Vue d’ensemble','appointments':'Rendez-vous','liveFloor':'Salle et ressources en direct','customers':'Clients','details':'Détails','item':'Élément','items':'éléments','unableLoad':'Impossible de charger','scanCheckInQr':'Scanner le QR d’arrivée','scanQrHint':'Scannez le QR signé de la réservation du client à son arrivée.','checkInSuccess':'Client enregistré avec succès','scanAnother':'Scanner un autre','toggleTorch':'Activer la lampe','switchCamera':'Changer de caméra','cameraUnavailable':'Caméra indisponible ou autorisation refusée','payouts':'Paiements professionnels','addCommission':'Ajouter une commission','createPayout':'Créer un paiement','standardCommission':'Commission standard','ruleName':'Nom de la règle','professional':'Professionnel','allProfessionals':'Tous les professionnels','commissionType':'Type de commission','percentage':'Pourcentage','fixedAmount':'Montant fixe','commissionValue':'Taux / montant','cancel':'Annuler','save':'Enregistrer','commissionCreated':'Règle de commission créée','noProfessionals':'Aucun professionnel actif','periodStart':'Début de période','periodEnd':'Fin de période','reference':'Référence','markPaid':'Marquer comme payé','payoutCreated':'Paiement créé','customer':'Client','recentAppointments':'Rendez-vous récents','appointment':'Rendez-vous','recentPayments':'Paiements récents','noBranches':'Aucune succursale active','branch':'Succursale','schedule':'Horaire','start':'Début','end':'Fin','scheduleSaved':'Horaire enregistré','commission':'Commission','commissionUpdated':'Commission mise à jour','editService':'Modifier le service','serviceName':'Nom du service','durationMinutes':'Durée en minutes','price':'Prix','depositPercent':'Acompte %','serviceUpdated':'Service mis à jour'
  },
};

String bt(BuildContext context, String key) {
  final code = Localizations.localeOf(context).languageCode;
  return _strings[code]?[key] ?? _strings['en']?[key] ?? key;
}
