import 'package:flutter/material.dart';
import 'lookiva_api.dart';
import 'l10n.dart';

class BusinessRemotePage extends StatelessWidget{final String section;const BusinessRemotePage({super.key,required this.section});@override Widget build(BuildContext context){final config=BusinessRemoteBody.configFor(section);return Scaffold(appBar:AppBar(title:Text(bt(context,config.titleKey))),body:BusinessRemoteBody(section:section));}}
class BusinessRemoteBody extends StatefulWidget{
  final String section;const BusinessRemoteBody({super.key,required this.section});
  static const config=<String,({String titleKey,String path,IconData icon})>{
    'overview':(titleKey:'overview',path:'/business-ops/{companyId}/overview',icon:Icons.dashboard_rounded),'calendar':(titleKey:'appointments',path:'/business-ops/{companyId}/appointments',icon:Icons.calendar_month_rounded),'floor':(titleKey:'liveFloor',path:'/business-ops/{companyId}/resources',icon:Icons.chair_rounded),'customers':(titleKey:'customers',path:'/business-ops/{companyId}/customers',icon:Icons.people_alt_rounded),'professionals':(titleKey:'professionals',path:'/business-ops/{companyId}/professionals',icon:Icons.badge_outlined),'services':(titleKey:'services',path:'/business-ops/{companyId}/services',icon:Icons.design_services_rounded),'payments':(titleKey:'payments',path:'/business-ops/{companyId}/payments',icon:Icons.payments_rounded),'promotions':(titleKey:'promotions',path:'/business-ops/{companyId}/promotions',icon:Icons.local_offer_rounded),'reviews':(titleKey:'reviews',path:'/business-ops/{companyId}/reviews',icon:Icons.reviews_outlined),'staff':(titleKey:'staff',path:'/business-ops/{companyId}/staff',icon:Icons.admin_panel_settings_outlined),'branches':(titleKey:'branches',path:'/business-ops/{companyId}/branches',icon:Icons.storefront_rounded),'subscription':(titleKey:'subscription',path:'/business-ops/{companyId}/subscriptions',icon:Icons.workspace_premium_outlined),'audit':(titleKey:'audit',path:'/business-ops/{companyId}/audit',icon:Icons.fact_check_outlined),'finance':(titleKey:'finance',path:'/finance-v2/companies/{companyId}/reconciliation',icon:Icons.account_balance_wallet_outlined),'analytics':(titleKey:'analytics',path:'/analytics-v2/companies/{companyId}/dashboard',icon:Icons.analytics_outlined),'queue':(titleKey:'queue',path:'/booking-v2/queues/{branchId}',icon:Icons.groups_rounded),'notifications':(titleKey:'notifications',path:'/notifications',icon:Icons.notifications_none_rounded)};
  static ({String titleKey,String path,IconData icon}) configFor(String section)=>config[section]??config['overview']!;
  @override State<BusinessRemoteBody> createState()=>_BusinessRemoteBodyState();
}
class _BusinessRemoteBodyState extends State<BusinessRemoteBody>{late Future<dynamic> _future;({String titleKey,String path,IconData icon})get config=>BusinessRemoteBody.configFor(widget.section);@override void initState(){super.initState();_reload();}@override void didUpdateWidget(covariant BusinessRemoteBody oldWidget){super.didUpdateWidget(oldWidget);if(oldWidget.section!=widget.section)_reload();}void _reload()=>_future=LookivaBusinessApi.instance.getScoped(config.path);
  @override Widget build(BuildContext context)=>FutureBuilder<dynamic>(future:_future,builder:(context,snapshot){if(snapshot.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(snapshot.hasError)return Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.cloud_off_rounded,size:52,color:Theme.of(context).colorScheme.error),const SizedBox(height:12),Text(LookivaBusinessApi.instance.friendlyError(snapshot.error!),textAlign:TextAlign.center),const SizedBox(height:16),ElevatedButton.icon(onPressed:()=>setState(_reload),icon:const Icon(Icons.refresh_rounded),label:Text(bt(context,'retry')))])));final rows=_rows(context,snapshot.data);return RefreshIndicator(onRefresh:()async{setState(_reload);await _future;},child:rows.isEmpty?ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(24),children:[const SizedBox(height:120),Icon(config.icon,size:56,color:Theme.of(context).colorScheme.primary),const SizedBox(height:14),Text(bt(context,'noRecords'),textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18))]):ListView.separated(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(16),itemCount:rows.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,index){final row=rows[index];return Card(child:ListTile(leading:Icon(config.icon,color:Theme.of(context).colorScheme.primary),title:Text(row.$1,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:row.$2.isEmpty?null:Text(row.$2,maxLines:5,overflow:TextOverflow.ellipsis)));}));});
  List<(String,String)> _rows(BuildContext context,dynamic value){if(value is List)return value.map((e)=>_summarize(context,e)).toList();if(value is Map){final map=Map<String,dynamic>.from(value);return map.entries.map((entry){if(entry.value is Map||entry.value is List)return(_label(entry.key),_compact(context,entry.value));return(_label(entry.key),entry.value?.toString()??'—');}).toList();}if(value==null)return const[];return[(bt(context,'details'),value.toString())];}
  (String,String)_summarize(BuildContext context,dynamic item){if(item is! Map)return(bt(context,'item'),item.toString());final map=Map<String,dynamic>.from(item);final title=_first(map,['display_name','name','full_name','status','id'])?.toString()??bt(context,'item');final details=<String>[];for(final key in['status','starts_at','currency_code','amount','base_price','created_at']){if(map[key]!=null)details.add('${_label(key)}: ${map[key]}');if(details.length==3)break;}return(title,details.join(' • '));}
  dynamic _first(Map<String,dynamic> map,List<String> keys){for(final key in keys){if(map[key]!=null&&map[key].toString().isNotEmpty)return map[key];}return null;}String _compact(BuildContext context,dynamic value){if(value is List)return'${value.length} ${bt(context,'items')}';if(value is Map)return value.entries.take(5).map((e)=>'${_label(e.key.toString())}: ${e.value}').join(' • ');return value?.toString()??'—';}String _label(String value)=>value.replaceAll('_',' ').split(' ').map((w)=>w.isEmpty?w:'${w[0].toUpperCase()}${w.substring(1)}').join(' ');
}
