'use client';
import * as React from 'react';
import Link from 'next/link';
import { useLocale, useTranslations } from 'next-intl';
import axios from '@/lib/axios';
export default function DiscoverPage(){
  const locale=useLocale();const t=useTranslations('discoverFeed');const[posts,setPosts]=React.useState<any[]>([]);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState('');
  React.useEffect(()=>{axios.get('/social/posts',{params:{limit:30}}).then(r=>setPosts(Array.isArray(r.data)?r.data:(r.data?.items||[]))).catch(e=>setError(e instanceof Error?e.message:t('loadError'))).finally(()=>setLoading(false));},[t]);
  return <div className="mx-auto max-w-3xl px-4 py-6"><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-accent-gold-2">{t('eyebrow')}</p><h1 className="mt-2 text-3xl font-bold text-primary">{t('title')}</h1><p className="mt-2 text-secondary">{t('subtitle')}</p></div>{loading&&<div className="space-y-4">{[1,2,3].map(i=><div key={i} className="h-[420px] animate-pulse rounded-radius-2xl bg-surface-2"/>)}</div>}{error&&<div className="rounded-radius-xl border border-accent-red/30 bg-accent-red/10 p-5 text-accent-red">{error}</div>}{!loading&&!error&&posts.length===0&&<div className="rounded-radius-xl border border-border-subtle bg-surface-1 p-10 text-center text-muted">{t('empty')}</div>}<div className="space-y-5">{posts.map((p:any)=><article key={p.id} className="overflow-hidden rounded-radius-2xl border border-border-subtle bg-surface-1"><div className="aspect-[4/5] bg-surface-2 flex items-center justify-center text-muted">{p.media?.[0]?.url?<img src={p.media[0].url} alt={p.caption||t('lookAlt')} className="h-full w-full object-cover"/>:<span>{t('media')}</span>}</div><div className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-primary">{p.professional?.display_name||p.author?.full_name||t('professional')}</p><p className="mt-1 text-sm text-secondary">{p.caption||t('published')}</p></div><span className="text-sm text-muted">♥ {p.like_count??p.likes_count??0}</span></div>{(p.service_ids?.[0]||p.services?.[0]?.service_id)&&<Link href={`/${locale}/book/${p.service_ids?.[0]||p.services?.[0]?.service_id}`} className="mt-4 inline-flex rounded-radius-md bg-accent-gold-2 px-4 py-2 text-sm font-semibold text-surface-0">{t('bookLook')}</Link>}</div></article>)}</div></div>;
}
